export const tableData = {
  data: [
    {
      id: 1,
      car_id: "HFJKAHAK6872431",
      instock: true,
      hp: 200,
      price: 50000,
      currency: "€",
      color: "red",
    },
    {
      id: 2,
      car_id: "HFJKAHAK6872432",
      instock: false,
      hp: 250,
      price: 70000,
      currency: "€",
      color: "blue",
    },
    {
      id: 3,
      car_id: "HFJKAHAK6872433",
      instock: false,
      hp: 100,
      price: 30000,
      currency: "€",
      color: "red",
    },
    {
      id: 4,
      car_id: "HFJKAHAK6872434",
      instock: true,
      hp: 150,
      price: 40000,
      currency: "€",
      color: "green",
    },
    {
      id: 5,
      car_id: "HFJKAHAK6872435",
      instock: false,
      hp: 140,
      price: 45000,
      currency: "€",
      color: "silver",
    },
  ],
};
